### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/PocketMine-MP#1]
Add names here
One comment per name. vote with thumbs up/down

**Comment by starterdragon** [comment]
Aurora

**Comment by starterdragon** [comment]
Constellation

**Comment by starterdragon** [comment]
Galaxy

**Comment by thebigsmileXD** [comment]
Cherry-pick

**Comment by thebigsmileXD** [comment]
Apocolypse

**Comment by thebigsmileXD** [comment]
thunderstorm

**Comment by thebigsmileXD** [comment]
NightSky

**Comment by thebigsmileXD** [comment]
Starlight/Moonlight

**Comment by starterdragon** [comment]
Downfall

**Comment by starterdragon** [comment]
Blizzard

**Comment by starterdragon** [comment]
FullMoon

**Comment by starterdragon** [comment]
Bluemoon

**Comment by Aericio** [comment]
git-cherry-pick

**Comment by thebigsmileXD** [comment]
@Aericio blamedktapps

**Comment by Aericio** [comment]
typo

**Comment by Aericio** [comment]
`ClearSky: Project Typo`

**Comment by Aericio** [comment]
It's another nice day in Germany, where @thebigsmileXD doing what he normally does... What a peaceful day it seems, until... `x50 GIT-CHERRY-PICK`

**Comment by thebigsmileXD** [comment]
'update from button'

**Comment by dktappsischildish** [comment]
'pmmp - modified by the ClearSkyTeam'

**Comment by thebigsmileXD** [comment]
Vote ends on 21st January

**Comment by starterdragon** [comment]
ClearSky : Realm

**Comment by Aericio** [comment]
ClearSky: Git

**Comment by Aericio** [comment]
@Aericio dfijsdjif dammit

**Comment by thebigsmileXD** [comment]
https://goo.gl/forms/M77MohXYGESTlRzo2
