### ISSUE TITLE
Stacked items remove on join (64 dirt changed 1)

### ISSUE THREAD

**Issue by andris155** [ClearSkyTeam/PocketMine-MP#100]
### Issue description

Stacked items remove on join (64 dirt changed 1)

### Steps to reproduce the issue

1. Stack 64 dirt
2. Rejoin
3. 64 dirt -> 1 dirt

### OS and versions

* PocketMine-MP: This server is running ClearSky-PocketMine-MP 1.7dev build #SELF-COMPILED 「[Heaven]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2.0RC4
* Server OS: Ubuntu 16.04.3 LTS

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
none

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by thebigsmileXD** [comment]
I can not reproduce this issue
