### ISSUE TITLE
Entity error

### ISSUE THREAD

**Issue by Crypt97** [ClearSkyTeam/PocketMine-MP#101]
### Issue description
Fatal error: Class 'pocketmine\entity\Projectile' not found in C:\Users\Crypthu\Desktop\PocketMine-MP-cs-1.2\src\pocketmine\entity\DragonFireball.php on line 8

### Steps to reproduce the issue

1. start server
2. watch console

### OS and versions

* PocketMine-MP: This server is running ClearSky-PocketMine-MP version 1.7dev 1.7dev build #SELF-COMPILED "[Heaven]" (API 3.0.0-ALPHA9)

* PHP: 7.2RC4
* Server OS: Ubuntu 16.04
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes

**Comment by thebigsmileXD** [comment]
From https://t.me/CSPhars:

> Warning: pmmp changed several things like Entity Spawning + Tile spawning, and also Projectiles. The next update will NOT work properly with the blocks / items added in ClearSky [Heaven], until updated to these methods

**Comment by thebigsmileXD** [comment]
Fixed
