### ISSUE TITLE
Fix AreaEffectCloud Particles

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/PocketMine-MP#22]
![image](https://cloud.githubusercontent.com/assets/8733998/22148692/e0dac296-df0f-11e6-9e56-329ed7438218.png)
![image](https://cloud.githubusercontent.com/assets/8733998/22148706/f10752ce-df0f-11e6-9881-67bcb053b095.png)
![image](https://cloud.githubusercontent.com/assets/8733998/22148712/f5df620a-df0f-11e6-94d5-4d732f28d3d7.png)
![image](https://cloud.githubusercontent.com/assets/8733998/22148722/035b0254-df10-11e6-955b-9b4a626efec1.png)
![image](https://cloud.githubusercontent.com/assets/8733998/22148723/071e9c84-df10-11e6-84c4-bbae3e83cb0f.png)

**Comment by thebigsmileXD** [comment]
Particles don't appear yet, AEC calculation + Lingering potions done.

**Comment by daniktheboss** [comment]
@thebigsmileXD :+1:

**Comment by thebigsmileXD** [comment]
On it.

**Comment by thebigsmileXD** [comment]
Did_not_work.exe

**Comment by thebigsmileXD** [comment]
Lol. Don't tell me it actually needs an effect to emit the effect particles? Why the fuck does every other particle work then?!

**Comment by thebigsmileXD** [comment]
The issue was the missing A of ARGB
