### ISSUE TITLE
Add Map (item)

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/PocketMine-MP#27]

**Comment by thebigsmileXD** [comment]
#2

**Comment by thebigsmileXD** [comment]
Whoops, gotta update this

**Comment by thebigsmileXD** [comment]
//MapItemSavedData::save
mapId
parentMapId
dimension
xCenter
zCenter
scale
width
height
colors
fullyExplored
data
key
decorations

//MapItemSavedData::TrackedMapEntity
type
entityId
blockX
blockY
blockZ

//MapItemSavedData::tickCarriedBy(Entity &,ItemInstance &)
id
xyz
rot
z
color
type
label

//MapConstants::HALF_MAP_SIZE
//MapConstants::MAX_SCALE

//decoration with color:Color::WHITE

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/22586476/44a5bf0e-e9fd-11e6-9a0c-52662237b344.png)
![image](https://cloud.githubusercontent.com/assets/8733998/22586478/47ee5662-e9fd-11e6-86a5-91558148aa64.png)

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/PocketMine-MP/tree/maps Almost fully done

**Comment by thebigsmileXD** [comment]
I made the plugin "MapAPI" for that. Servers themself would lag out too much. Maybe in the future.
