### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by caspervanneck** [ClearSkyTeam/PocketMine-MP#31]
will this ever done in old group or get the cloned

**Comment by thebigsmileXD** [comment]
@caspervanneck What

**Comment by caspervanneck** [comment]
it is cloned or is it mergt the old repo @thebigsmileXD

**Comment by caspervanneck** [comment]
PS I miss ClearSky really much

**Comment by caspervanneck** [comment]
@thebigsmileXD if you need any help invite me :p

**Comment by thebigsmileXD** [comment]
What the fuck,.. what?!

**Comment by Aericio** [comment]
LOL INVITE YOU I CRINGE

**Comment by caspervanneck** [comment]
Wtf @Aericio  why are you ...   Btw i say if he needs it so shut up.

**Comment by thebigsmileXD** [comment]
Another word -> banned from repo.
