### ISSUE TITLE
Phar

### ISSUE THREAD

**Issue by lolmanz0** [ClearSkyTeam/PocketMine-MP#47]
Where can I download the latest phar? Link in the description is not valid...

**Comment by thebigsmileXD** [comment]
@lolmanz0 Dan:
FUCKING RELEASE:
https://github.com/ClearSkyTeam/PocketMine-MP/releases/tag/MCPE1.0.3-pre1.0.4

**Comment by lolmanz0** [comment]
Thx. I will know where to download next time.

**Comment by thebigsmileXD** [comment]
@lolmanz0 Sorry if i sounded mean, i simply copied the attached message of our telegram group.

**Comment by lolmanz0** [comment]
XD No, lol, you told me where can I download compiled software. I am happy! (In releases.)
