### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by AppleDevelops** [ClearSkyTeam/PocketMine-MP#49]
Alright, so I've been giving away a plugin that requires some functions. If you could add those that'd be great. https://github.com/TesseractTeam/Tesseract/commit/15252a4a041d66b6813c38984783d74852dae9b9

**Comment by thebigsmileXD** [comment]
Can you ask @ https://github.com/pmmp/PocketMine-MP directly? i dont want to change network stuff for less reasons.

**Comment by AppleDevelops** [comment]
I'm not so sure if they'd do it. I'll just make a workaround in my plugin.

**Comment by thebigsmileXD** [comment]
i think those values are pretty cool, i kind of look forward for them being added
