### ISSUE TITLE
Command Blocks

### ISSUE THREAD

**Issue by LagHD** [ClearSkyTeam/PocketMine-MP#52]
Command Blocks have been added to 1.0.5 beta! Can you add them to ClearSky?

**Comment by thebigsmileXD** [comment]
@LagHD Wtf. 1.0.5 doesnt exist and what kind of scam news are you watching on youtube..

**Comment by Aericio** [comment]
1.0.5 IS FUCKEN BETA LOL

**Comment by caspervanneck** [comment]
Yes it's in beta so @LagHD wait

**Comment by LagHD** [comment]
Yeah ik lol, next time I'll write in more detail...

**Comment by LagHD** [comment]
@thebigsmileXD 1.0.5 is out in beta

**Comment by thebigsmileXD** [comment]
@LagHD i dont care in any way

**Comment by thebigsmileXD** [comment]
@thebigsmileXD because its just a skinpack update -.-

**Comment by xinghao2003** [comment]
no , it really have command block

**Comment by thebigsmileXD** [comment]
@xinghao2003 well, i can't open/generate any worlds, all my worlds and servers are wiped. gg mojang

**Comment by thebigsmileXD** [comment]
WHAT. THE. FUCK. Now a world finally loaded.. and.. shit you are right, and they work perfectly!!!! Oh lord why. Mojang is a bit stupid, aren't they? Can't get Auto-Saving done but add command blocks..

**Comment by LagHD** [comment]
It's sad that I can't take part in new beta builds tho they seems to auto crash but official releases work 😃

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP/commit/e7dbda922a5e8eb4a2f7e5529c6965febdbaac8b

Seems like they will be added by @dktapps..

**Comment by LagHD** [comment]
Ok thanks

**Comment by LagHD** [comment]
Let me know when they are added 😃

**Comment by thebigsmileXD** [comment]
@LagHD Dude. Chill your balls, 1.15 is JUST out and Github will send you update notifications on that issue..

**Comment by thebigsmileXD** [comment]
@LagHD I mean 1.5.bla beta

**Comment by LagHD** [comment]
Ok, btw 1.0.5.3 is out in beta now lol

**Comment by thebigsmileXD** [comment]
@LagHD B.E.T.A. Stop spamming + annoying!

**Comment by thebigsmileXD** [comment]
Closing for spam. See #2

**Comment by Aericio** [comment]
Ok, btw 1.0.5.3.0 is out in beta now lol

**Comment by LagHD** [comment]
No lol your closing it because u dislike me or u have a problem with my issue, oh well as long as it's being worked on.

**Comment by thebigsmileXD** [comment]
@LagHD Sorry, but are you retarded? Can you read? Wtf. MCPE is STILL beta, and i wait for pmmp, also you spam every second day 'finist now?'
