### ISSUE TITLE
New Commands

### ISSUE THREAD

**Issue by LagHD** [ClearSkyTeam/PocketMine-MP#54]
So as MCPE 1.0.5 Recently Came Out, will we be getting the new commands like /title, /gamerule, etc?

**Comment by SuperKali** [comment]
@LagHD Add title? Wow

**Comment by Aericio** [comment]
@LagHD Yes Sherlock, 1.0.5 came out please stop making issues on this.

**Comment by thebigsmileXD** [comment]
@SuperKali yes

**Comment by SuperKali** [comment]
@thebigsmileXD Good👍

**Comment by LagHD** [comment]
Lol, Sorry
