### ISSUE TITLE
Unable to craft items

### ISSUE THREAD

**Issue by bowenqiang** [ClearSkyTeam/PocketMine-MP#56]
### Issue description

Unable to craft any items

Notice: Undefined offset: 0 in /home/pi/git/pocketmine-mp.CST/src/pocketmine/Player.php on line 2794
### Steps to reproduce the issue

1. ...login in server
2. ...craft

### OS and versions

* PocketMine-MP: ClearSky-PocketMine-MP 1 .6.2dev 「Aurora」 implementing API version 3.0.0-ALPHA4 for Minecraft: PE v1.0. 5.0 beta (protocol version 105)
* PHP:  PHP7

* Server OS: Raspberry Pi  Raspbian GNU/Linux 8.0 (jessie)
* Game version: Minecraft Win10 Edition v1.0.5

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment]
@bowenqiang See pocketmine issue list

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP/issues/45
