### ISSUE TITLE
I can fishing with ClearSky.

### ISSUE THREAD

**Issue by jdongel2004** [ClearSkyTeam/PocketMine-MP#58]
### Issue description

 I can fishing with Clearsky. (Not pmmp fork) @thebigsmileXD.. Can you add this? 

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 1.6.2 dev
* PHP: 7.0.17
* Server OS: Ubuntu 16.10
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment]
First: did'nt properly use the preset layout
Second: great grammar
3rd: no. Also see #2
