### ISSUE TITLE
I can't use command.

### ISSUE THREAD

**Issue by jdongel2004** [ClearSkyTeam/PocketMine-MP#60]
### Issue description

 Some plugins , I can't use command. Example, write /announce . Nothing appears. ( plugins was load.) I

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: clearsky forked PocketMine-MP
* PHP: 7.0.17
* Server OS: Ubuntu 16.10 x64
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...
 Nothing

**Comment by thebigsmileXD** [comment]
Didn't use template. Invalid.

**Comment by Aericio** [comment]
i like the random "I" at the end of the sentence
