### ISSUE TITLE
Fix CircleCI build, #blamecircleci

### ISSUE THREAD

**Issue by ZaneWalter** [ClearSkyTeam/PocketMine-MP#69]
Please provide the .phar file for ClearSky.

**Comment by Aericio** [comment]
@ZaneWalter exzdee plz add too dumb to read readme.md

**Comment by thebigsmileXD** [comment]
@ZaneWalter Please read the readme.

**Comment by ZaneWalter** [comment]
Thank you for reopening.

**Comment by thebigsmileXD** [comment]
@ZaneWalter Build it yourself.

**Comment by ZaneWalter** [comment]
I can't. My host wont let me.

**Comment by thebigsmileXD** [comment]
@ZaneWalter Then get another host because yours is useless

**Comment by ZaneWalter** [comment]
@thebigsmileXD I am finding one trust me.

**Comment by thebigsmileXD** [comment]
Fixed and fucked up again. Yay.

**Comment by thebigsmileXD** [comment]
done and dusted, group gets the file sendt directly
