### ISSUE TITLE
Fix AsyncTask.php!

### ISSUE THREAD

**Issue by Deeonix** [ClearSkyTeam/PocketMine-MP#70]
[Server thread/CRITICAL]: RuntimeException: "pthreads detected an attempt to connect to an object which has already been destroyed" (EXCEPTION) in "/src/pocketmine/scheduler/AsyncTask" at line 98

Please Fix this line exxdee :D

**Comment by thebigsmileXD** [comment]
@Deeonix looks like your plugins bug around. disable all and check if it still appears

**Comment by thebigsmileXD** [comment]
Checked. Plugin fault
