### ISSUE TITLE
Add inventory reset on gamemode change!!

### ISSUE THREAD

**Issue by ZaneWalter** [ClearSkyTeam/PocketMine-MP#72]
### Issue description

Please add so whenever a player changes gamemode his/her inventory would also reset.

**Comment by thebigsmileXD** [comment]
@ZaneWalter NO!!!

**Comment by thebigsmileXD** [comment]
Do it as a plugin..

Kyrobi!, [15.05.17 21:50]
[Antwort auf GitHub]
Add it yourself
