### ISSUE TITLE
add dropper?

### ISSUE THREAD

**Issue by XDqrkneZ** [ClearSkyTeam/PocketMine-MP#85]
### Steps to reproduce the issue

1. ... add dropper
2. ... i need droppers for my server so please, add it if you can :)! keep the good work.. this is by far the most stabled software ive tried

### OS and versions

* PocketMine-MP: ClearSky-PocketMine-MP 1.6.2dev [#635db92 2017-06-24] 「Aurora」 implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment]
#2 #24

**Comment by XDqrkneZ** [comment]
thanks
