### ISSUE TITLE
AntiCheat

### ISSUE THREAD

**Issue by BlawoHD** [ClearSkyTeam/PocketMine-MP#88]
### Issue description

The AntiCheat is broken, can you fix it or take it out?
### Steps to reproduce the issue

1. pocketmine.yml set to allow-movement-cheats: true and to allow-instabreak: true
2. start the server and join ingame

### OS and versions

* PocketMine-MP: https://github.com/ClearSkyTeam/PocketMine-MP/commit/f98db898a552b5c996db07a5dc53ab3b3ccc54e2
* PHP: 7.0.6
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment]
Please add more and better information
