### ISSUE TITLE
Kicking for flying! WHEN I AM NOT FLYING!

### ISSUE THREAD

**Issue by CyanCreeper** [ClearSkyTeam/PocketMine-MP#89]
### Steps to reproduce the issue

1. ...23.07 17:46:47 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in phar:///jar/pocketmine/clearsky/1.1.0/ClearSky.phar/src/pocketmine/entity/Entity.php on line 984" (EXCEPTION) in "src/pocketmine/entity/Living" at line 103
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...23.07 17:46:47 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in phar:///jar/pocketmine/clearsky/1.1.0/ClearSky.phar/src/pocketmine/entity/Entity.php on line 984" (EXCEPTION) in "src/pocketmine/entity/Living" at line 103

**Comment by Aericio** [comment]
Fill out the issue template completely.

**Comment by thebigsmileXD** [comment]
Flying: A problem by PocketMine itself, please read the pocketmine docs and pocketmine.yml. Issue content has nothing to do with title.
