### ISSUE TITLE
Add Enderchest Items to Player NBT, Block, Tile

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/PocketMine-MP#9]
Player NBT
Enderchest

**Comment by starterdragon** [comment]
can't wait for this

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/22148817/9eff57b4-df10-11e6-8c8b-7cc3d3fc3d06.png)
Tile
